## makeCacheMatrix and cacheSolve get and output matrix and its inverse 
## matrix and inverse are store in cache

## makeCacheMatrix set and output data

makeCacheMatrix <- function(matrx= matrix()) {
    invs <- NULL
    set <- function(y) {
        matrx <<- y
        invs <<- NULL
    }
    get <- function() matrx
    setinvs <- function(inversematrix) invs <<- inversematrix
    getinvs <- function() invs
    list(set = set, get = get,
         setinvs = setinvs,
         getinvs = getinvs)

}


## calculate the inverse of matrx with input x generated by makeCacheMatrix function

cacheSolve <- function(x, ...) {
    invs <- x$getinvs()
    if(!is.null(invs)) {
        message("getting cached inverse of the matrix")
        return(invs)
    }
    data <- x$get()
    invs <- solve(data)
    x$setinvs(invs)
    invs
}
